### ISSUE TITLE
Typescript issue export declare const MODE: checkout/types/constants.d.ts

### ISSUE THREAD

**Issue by ronakamlani** [revolut-engineering/revolut-checkout#10]
Hi, today I am receiving the following error during "next build" I am not sure, this error is all about.

```
./node_modules/@revolut/checkout/types/constants.d.ts 1:7
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently, no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export declare const MODE: {
|     PRODUCTION: "prod";
|     DEVELOPMENT: "dev";
```

Please please guys help me to come out.

Thanks

**Comment by ohansemmanuel** [comment]
@ronakamlani could you please share what version of `revolut-checkout` you're running in your `nextjs` project? 

Also, did this error begin after an upgrade of either `revolut-checkout` or `nextjs` ? 

Many thanks

**Comment by ronakamlani** [comment]
The error has been resolved by
`import RevolutCheckout from '@revolut/checkout/cjs'`

Rather then,
`import RevolutCheckout from '@revolut/checkout'`
