### ISSUE TITLE
CORS error in servers

### ISSUE THREAD

**Issue by vgpastor** [revolut-engineering/revolut-checkout#15]
Hi.

I'm developing an Angular PWA, but i can't test the API because ours servers haven't use CORS policies that it's required for modern browsers.

You can te here your CORS policy and show the error.
https://www.test-cors.org/#?client_method=POST&client_credentials=false&client_headers=Content-Type%3Aapplication%2Fjson%3B%20charset%3Dutf-8%0AAuthorization%3ABearer%20sk_X8MvhJc0I0-cKP-pcIOI0EGShczt59XLHX3MLsmaGTS4VhJ872aTlFJJDrDmIOVM&client_postdata=%7B%0A%09%22amount%22%3A%20101%2C%0A%09%22currency%22%3A%20%22EUR%22%0A%7D&server_url=https%3A%2F%2Fsandbox-merchant.revolut.com%2Fapi%2F1.0%2Forders&server_enable=false&server_status=200&server_credentials=false&server_tabs=remote

Regards!

**Comment by ohansemmanuel** [comment]
Thanks for the report @vgpastor 

Can you confirm that you're making the request to the `/orders` endpoint  (create order) from your server and not the client (Angular PWA) ?
