### ISSUE TITLE
Sandbox embed script link is down

### ISSUE THREAD

**Issue by wow0000** [revolut-engineering/revolut-checkout#7]
Dear sir or madam,
The embed.js script for sandbox is currently down and return a 404 error. [Link](https://github.com/revolut-engineering/revolut-checkout/blob/87163d6f7942a779dcbc0ada240e8a5f2beeca9c/src/constants.ts#L10)
It is currently in use in the `src/constants.ts` file which is linked above.

Both of the dev and prod script are working.
Best Regards,

**Comment by ohansemmanuel** [comment]
Thanks for raising the issue @wow0000  
The team has resolved this. The `embed.js` script should load successfully on sandbox now. Please confirm on your end.

Cheers!

**Comment by wow0000** [comment]
Thank you !
I do confirm that sandbox mode is now working nicely

Have a nice day !
